# Generated by Codex on 2025-11-09

from django.conf import settings
from django.core.management import call_command
from django.db import migrations


def create_initial_superuser(apps, schema_editor):
    """
    Crée un superutilisateur en production lorsque les variables d'environnement
    DJANGO_SUPERUSER_* sont définies. Sans ces variables (ex: en local),
    cette migration est un no-op.
    """
    username = getattr(settings, "DJANGO_SUPERUSER_USERNAME", None)
    email = getattr(settings, "DJANGO_SUPERUSER_EMAIL", None)
    password = getattr(settings, "DJANGO_SUPERUSER_PASSWORD", None)
    role = getattr(settings, "DJANGO_SUPERUSER_ROLE", "director")

    if not (username and email and password):
        return

    call_command(
        "createsu",
        username=username,
        email=email,
        password=password,
        role=role,
    )


def noop(apps, schema_editor):
    """Rollback no-op."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_remove_attachment_storage_delivery_type"),
    ]

    operations = [
        migrations.RunPython(create_initial_superuser, noop),
    ]
